# Fishing rod structure:
# {display-name} &f(&7Level {level}&f)
#  Lore:e
#  - {lore} -- The lore defined in the rod configuration
#  - ""
#  - "&e&lExperience: &3{current}&f/&c{required}
#  - ""
#  - "&7Perks:"
#  - ""
#  - {perks}
#  - {perks}
#  - etc.

# Must have one rod with a minimum-level of 1

old-rod:
  minimum-level: 1 # No need to set maximum, as the next milestone would do that
  display-name: "&b&lOld Rod"
  lore:
    - ""
    - "An old, rusted rod."
  drop-table: # Chances are weighted, so the chance an item will drop is determined by percent of total weight.
    #"1": -- Can be named whatever you like. I would recommend an identifying name, such as two-ink-sac or one-coal-node
      #item: aoWDACmwdmwaodj # Serialized itemstack
     # weight: 20.00 # Double
     # experience: 40.00 # Double