name: HSFishing
version: '${project.version}'
main: net.highskiesmc.hsfishing.HSFishing
api-version: 1.13
authors: [ Daniel Ohrin ]
depend: [ Quests ]
commands:
  hsfishing:
    aliases:
      - hsf
  upgraderod: